from typing import Dict, Iterable
from io import StringIO


# List of SOL shill usernames provided by the user
SOL_SHILLS = [
    "@0xSweep",
    "@0xzZyat",
    "@38v4So5Kt",
    "@9trew",
    "@_thespac",
    "@abawebs",
    "@abgwebs",
    "@abrarthec",
    "@adameshelton",
    "@Advyth",
    "@aenuinedegen",
    "@ahostassassinn",
    "@aisercore",
    "@aleexsix",
    "@aleywebs",
    "@aleywors",
    "@ApeMP5",
    "@apemps",
    "@arcane_c",
    "@Arcane_Crypto_",
    "@astawebs",
    "@astro_nu",
    "@Atitty",
    "@atitty_",
    "@atsarcore",
    "@azgloban",
    "@bagcalls",
    "@bazza_aped",
    "@bazza_ay",
    "@bitcoinza",
    "@Biteoinzac",
    "@Block100x",
    "@bloodweb3",
    "@bloodwet",
    "@bon",
    "@bon_g",
    "@brommm",
    "@brommmyy",
    "@Bronsixbt",
    "@Brookcalls",
    "@broskisol",
    "@bruca",
    "@bryanros",
    "@bryanrosswins",
    "@busraeth",
    "@bysukie",
    "@c_potens",
    "@Capitalist",
    "@capitalistog",
    "@Cardcabz",
    "@cardcabz",
    "@cometealls",
    "@cottonxbt",
    "@cryplobul",
    "@Crypto_ED7",
    "@CryptoAnalio",
    "@cryptoazyra",
    "@CryptoBaldwinlY",
    "@cryptobul",
    "@cryptobullying",
    "@cryptoext",
    "@CryptoLady_M",
    "@cryptostorm",
    "@cryptowifeyx",
    "@Daokwon",
    "@DaoKwonDo",
    "@darky1k",
    "@Darky1k",
    "@de_rugger",
    "@dea_ape",
    "@deaenbrody",
    "@Decentralpapi",
    "@degencru",
    "@degencruise",
    "@dehkunle",
    "@deviled_megas",
    "@DMTLAND",
    "@DotComParker",
    "@drallio",
    "@dyorwami",
    "@eddyXBT",
    "@eih_danx",
    "@elhousesol",
    "@enpt0iace",
    "@eottonxbt",
    "@erypto_a",
    "@erypto_e",
    "@eryptolad",
    "@eryptopizzaairl",
    "@eryptopo",
    "@eryptosto",
    "@etrckk_c",
    "@evancrypt",
    "@EzMoneyGems",
    "@farmercis",
    "@ferreweb3",
    "@FezWeb3",
    "@Flowslike",
    "@flowslikeosmo",
    "@fuelkek",
    "@fwtyo",
    "@GemsScope",
    "@gG1PeMtQQY9E",
    "@ghostess",
    "@Goboovi",
    "@goodness",
    "@GoodnessDeFi",
    "@GryptoTony",
    "@HairHustler",
    "@HairHustler128_",
    "@hellernen",
    "@henrys0x",
    "@herrocryp",
    "@herrocrypto",
    "@hezr",
    "@HiswatDofa",
    "@hiswatdot",
    "@hubaity",
    "@iamehuc",
    "@iamiekingston",
    "@illlyvivvi",
    "@iockweos",
    "@ireryptex",
    "@its_braz",
    "@itsthurstxn",
    "@ix_wilson",
    "@jeremyyb",
    "@Jeremyybte",
    "@jetxbt",
    "@katherine",
    "@kokid951",
    "@krypto_hy",
    "@kryptohun",
    "@kuzoeth",
    "@lamehucky",
    "@leffnta",
    "@lefinta",
    "@leochaind",
    "@leochaint",
    "@leowebs",
    "@leowers_",
    "@Lin_DAO",
    "@lin_dao_",
    "@littlemust",
    "@lockedinlucas",
    "@lockedint",
    "@lockweb3",
    "@lowkeyric",
    "@lowkeyrich",
    "@luaweb3",
    "@luno_solt",
    "@lynkOx",
    "@lynkox",
    "@macee",
    "@marcellox1",
    "@marcex",
    "@matrixon",
    "@mattinwe",
    "@MattinWeb3",
    "@Mduz_NET",
    "@mduz_nt",
    "@mediagir",
    "@MediaGiraffes",
    "@mistooor",
    "@mobyme",
    "@MobyMedia",
    "@monstera",
    "@MonyWeb3",
    "@mooonda",
    "@mooondat",
    "@mortywet",
    "@mostangr",
    "@mowiweb3",
    "@mowkive",
    "@nbweb3",
    "@nbwebs",
    "@nfipriest_",
    "@nftoriest_1",
    "@noahhealls",
    "@notdecu",
    "@notEezzy",
    "@oa_tery0",
    "@obeyauyy",
    "@obeyguyy",
    "@odicrypt",
    "@oexghost",
    "@officialsky",
    "@officialskywee1",
    "@offshoda",
    "@oGTerryox",
    "@ohouses",
    "@ola_crrypt",
    "@Ony3oku",
    "@oryploda",
    "@oryptoton",
    "@OxSweep",
    "@Oxxhost",
    "@OxZyaf",
    "@oyptojac",
    "@parcifap_defi",
    "@Parsa_Nfit",
    "@praxmedia",
    "@president",
    "@princeracks",
    "@purpurrp",
    "@queencry",
    "@raintures",
    "@realpablo",
    "@realpabloheman",
    "@Regrets10x",
    "@regrets1C",
    "@rentowth",
    "@renzosalp",
    "@renzosalpha",
    "@Rizzyic",
    "@Roarweb3",
    "@roarwebs",
    "@romejayx",
    "@rozer100x",
    "@rozert00",
    "@rP9k3k",
    "@rutradebt",
    "@rutradebtc",
    "@rypto",
    "@rypto_",
    "@s0B00",
    "@satoshiov",
    "@Satoshiowl",
    "@selor",
    "@seph_jim",
    "@sephjim",
    "@SexyMichill",
    "@shmoonft",
    "@ShmooNt",
    "@sibeleth",
    "@soapweb",
    "@soapweb3",
    "@SOLFistc",
    "@SOLFisTooShort_",
    "@solidtrad",
    "@solidtradesz",
    "@sorambil",
    "@spond",
    "@steezehur",
    "@stevenas",
    "@stevenascher",
    "@Strew",
    "@tedadycley",
    "@TeddyCleps",
    "@tedpillow",
    "@TedPillows",
    "@TheDefia",
    "@TheDefiApe",
    "@tnzz",
    "@tomgenzx",
    "@trapjuices",
    "@trapjuicesol",
    "@trentownt",
    "@tunmi_f",
    "@tunmi_t",
    "@tvbzify",
    "@uallstreet",
    "@ubzity",
    "@uxdubem",
    "@vainyz",
    "@vasta",
    "@vee",
    "@vikinaxbt",
    "@wasted0x",
    "@web3ma",
    "@Web3Maxx",
    "@web3righteous",
    "@webowan",
    "@webwarior",
    "@WisdomMatic",
    "@wisdomn",
    "@wtfisdave",
    "@wtfisdavee",
    "@xelf_sol",
    "@xiacalls",
    "@xxldubem",
    "@zacknfa",
    "@zacknia",
    "@zeusrebir",
    "@ZeusRebirth",
    "@ziyic",
]


def block_from_file(
    file_obj: Iterable[str], source_id: str, token: str
) -> Dict[str, str]:
    """Block users listed in ``file_obj``.

    This stub function reads each line from the provided file-like object and
    returns a mapping of username to a message indicating the user was blocked.
    The ``file_obj`` may yield either strings or bytes; bytes are decoded using
    UTF-8. In a real implementation this would call the X API using
    ``source_id`` and ``token``.
    """
    results: Dict[str, str] = {}
    for line in file_obj:
        if isinstance(line, bytes):
            line = line.decode("utf-8")
        username = line.strip()
        if not username:
            continue
        # Placeholder: real blocking logic would go here
        results[username] = "blocked"
    return results


def block_sol_shills(source_id: str, token: str) -> Dict[str, str]:
    """Block the preset list of SOL shill usernames."""

    buffer = StringIO("\n".join(SOL_SHILLS))
    return block_from_file(buffer, source_id, token)
